server:
  port: 8080
logging:
  level:
#    root: debug
    com.example.springexample: debug

#comment:
#  length:
#    max: 300
#
#app:
#  name: MyApp
#  maxConnections: 10
#  enableFeature: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox2
    username: skillbox
    password: skillbox
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    hibernate.ddl-auto: create
#    hibernate.ddl-auto: validate
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
#    drop-first: true
    drop-first: false